"""add_topic_name_to_articles

Revision ID: b9f2281f5214
Revises: c177df4fc6d8
Create Date: 2026-06-10 09:54:54.501457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f2281f5214'
down_revision: Union[str, None] = 'c177df4fc6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('topic_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_articles_topic_name'), 'articles', ['topic_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_topic_name'), table_name='articles')
    op.drop_column('articles', 'topic_name')
    # ### end Alembic commands ###
